//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.Forms.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xamarin.Forms.Exceptions.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Add() elements to &apos;{0}&apos;..
        /// </summary>
        internal static string AddElementsTo {
            get {
                return ResourceManager.GetString("AddElementsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot assign property &apos;{0}&apos;: Property does not exist, or is not assignable, or mismatching type between value and property..
        /// </summary>
        internal static string AssignProperty {
            get {
                return ResourceManager.GetString("AssignProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not a {1}..
        /// </summary>
        internal static string BadType {
            get {
                return ResourceManager.GetString("BadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding: Indexer did not contain arguments..
        /// </summary>
        internal static string BindingArguments {
            get {
                return ResourceManager.GetString("BindingArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding: Indexer did not contain closing bracket..
        /// </summary>
        internal static string BindingClosingBracket {
            get {
                return ResourceManager.GetString("BindingClosingBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the bindable property {0} does not ends with \&quot;Property\&quot;..
        /// </summary>
        internal static string BindingEndsProperty {
            get {
                return ResourceManager.GetString("BindingEndsProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding: {0} could not be parsed as an index for a {1}..
        /// </summary>
        internal static string BindingParse {
            get {
                return ResourceManager.GetString("BindingParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding: Property &apos;{0}&apos; not found on &apos;{1}&apos;..
        /// </summary>
        internal static string BindingPropertyNotFound {
            get {
                return ResourceManager.GetString("BindingPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding: Unsupported indexer index type: {0}..
        /// </summary>
        internal static string BindingUnsupportedType {
            get {
                return ResourceManager.GetString("BindingUnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No constructors found for {0} with matching x:Arguments.
        /// </summary>
        internal static string ConstructorsNotFound {
            get {
                return ResourceManager.GetString("ConstructorsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert type &apos;{0}&apos; to &apos;{1}&apos; via a reference conversion, boxing conversion, unboxing conversion, wrapping conversion, or null type conversion.
        /// </summary>
        internal static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x:DataType expects a string literal, an {{x:Type}} markup or {{x:Null}}..
        /// </summary>
        internal static string DataTypeStringLiteral {
            get {
                return ResourceManager.GetString("DataTypeStringLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not contain a definition for &apos;{1}&apos; and no extension method &apos;{2}&apos; accepting a first argument of type &apos;{0}&apos; could be found (are you missing a using directive or an assembly reference?)..
        /// </summary>
        internal static string Definition {
            get {
                return ResourceManager.GetString("Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a duplicate..
        /// </summary>
        internal static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} extension failed..
        /// </summary>
        internal static string ExtensionFailed {
            get {
                return ResourceManager.GetString("ExtensionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} extension not closed..
        /// </summary>
        internal static string ExtensionNotClosed {
            get {
                return ResourceManager.GetString("ExtensionNotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid..
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No method &apos;{0}&apos; with correct signature found on type &apos;{1}&apos;..
        /// </summary>
        internal static string MethodNotFound {
            get {
                return ResourceManager.GetString("MethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing public default constructor for &apos;{0}&apos;..
        /// </summary>
        internal static string MissingConstructor {
            get {
                return ResourceManager.GetString("MissingConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-valued enums are not valid on sbyte enum types.
        /// </summary>
        internal static string MultiEnumToSbyte {
            get {
                return ResourceManager.GetString("MultiEnumToSbyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple child elements in &apos;{0}&apos;..
        /// </summary>
        internal static string MultipleChild {
            get {
                return ResourceManager.GetString("MultipleChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires a non-null value to be specified for at least one idiom or Default..
        /// </summary>
        internal static string NonNullValue {
            get {
                return ResourceManager.GetString("NonNullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No resource found for &apos;{0}&apos;..
        /// </summary>
        internal static string NoResourceFoundFor {
            get {
                return ResourceManager.GetString("NoResourceFoundFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the object referenced by {0}..
        /// </summary>
        internal static string ObjectNotFound {
            get {
                return ResourceManager.GetString("ObjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is obsolete: &apos;{1}&apos;.
        /// </summary>
        internal static string Obsolete {
            get {
                return ResourceManager.GetString("Obsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property not set..
        /// </summary>
        internal static string PropertyNotSet {
            get {
                return ResourceManager.GetString("PropertyNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing a public static &apos;{0}&apos; or a public instance property getter for the attached property &apos;{0}&apos;..
        /// </summary>
        internal static string PublicStaticProperty {
            get {
                return ResourceManager.GetString("PublicStaticProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} only accepts Relative URIs..
        /// </summary>
        internal static string RelativeUriOnly {
            get {
                return ResourceManager.GetString("RelativeUriOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} require {1}..
        /// </summary>
        internal static string Requires {
            get {
                return ResourceManager.GetString("Requires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve name &apos;{0}&apos; of {1}..
        /// </summary>
        internal static string ResolveName {
            get {
                return ResourceManager.GetString("ResolveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve property &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string ResolveProperty {
            get {
                return ResourceManager.GetString("ResolveProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve type &apos;{0}&apos;..
        /// </summary>
        internal static string ResolveType {
            get {
                return ResourceManager.GetString("ResolveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A resource with the key &apos;{0}&apos; is already present in the {1}..
        /// </summary>
        internal static string ResourceAlreadyPresent {
            get {
                return ResourceManager.GetString("ResourceAlreadyPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource &apos;{0}&apos; not found..
        /// </summary>
        internal static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources in {0} require a x:Key attribute..
        /// </summary>
        internal static string ResourceRequireKey {
            get {
                return ResourceManager.GetString("ResourceRequireKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set the content of &apos;{0}&apos; as it doesn&apos;t have a &apos;{1}&apos;..
        /// </summary>
        internal static string SetContent {
            get {
                return ResourceManager.GetString("SetContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; not found for &apos;{1}&apos;..
        /// </summary>
        internal static string SomethingNotFound {
            get {
                return ResourceManager.GetString("SomethingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style property or Content is not a string literal..
        /// </summary>
        internal static string StyleOrContent {
            get {
                return ResourceManager.GetString("StyleOrContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleSheet requires either a Source or a content..
        /// </summary>
        internal static string StyleSheet {
            get {
                return ResourceManager.GetString("StyleSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax for {0} is {1}..
        /// </summary>
        internal static string Syntax {
            get {
                return ResourceManager.GetString("Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; already contains a definition for &apos;{1}&apos;.
        /// </summary>
        internal static string TypeAlreadyContains {
            get {
                return ResourceManager.GetString("TypeAlreadyContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No property, bindable property, or event found for &apos;{0}&apos;, or mismatching type between value and property..
        /// </summary>
        internal static string TypeMismatch {
            get {
                return ResourceManager.GetString("TypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeName is not set..
        /// </summary>
        internal static string TypeName {
            get {
                return ResourceManager.GetString("TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; not found in xmlns &apos;{1}&apos;..
        /// </summary>
        internal static string TypeNotFound {
            get {
                return ResourceManager.GetString("TypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undeclared xmlns prefix {0}..
        /// </summary>
        internal static string UndeclaredPrefix {
            get {
                return ResourceManager.GetString("UndeclaredPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined exception.
        /// </summary>
        internal static string UndefinedException {
            get {
                return ResourceManager.GetString("UndefinedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {0} but found {1}..
        /// </summary>
        internal static string Unexpected {
            get {
                return ResourceManager.GetString("Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x:Static: unable to find a public -- or accessible internal -- static field, static property, const or enum value named {0} in {1}..
        /// </summary>
        internal static string Xstatic {
            get {
                return ResourceManager.GetString("Xstatic", resourceCulture);
            }
        }
    }
}
