//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.Forms.Exceptions {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Xamarin.Forms.Exceptions.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AddElementsTo {
            get {
                return ResourceManager.GetString("AddElementsTo", resourceCulture);
            }
        }
        
        internal static string AssignProperty {
            get {
                return ResourceManager.GetString("AssignProperty", resourceCulture);
            }
        }
        
        internal static string BadType {
            get {
                return ResourceManager.GetString("BadType", resourceCulture);
            }
        }
        
        internal static string BindingArguments {
            get {
                return ResourceManager.GetString("BindingArguments", resourceCulture);
            }
        }
        
        internal static string BindingClosingBracket {
            get {
                return ResourceManager.GetString("BindingClosingBracket", resourceCulture);
            }
        }
        
        internal static string BindingEndsProperty {
            get {
                return ResourceManager.GetString("BindingEndsProperty", resourceCulture);
            }
        }
        
        internal static string BindingParse {
            get {
                return ResourceManager.GetString("BindingParse", resourceCulture);
            }
        }
        
        internal static string BindingPropertyNotFound {
            get {
                return ResourceManager.GetString("BindingPropertyNotFound", resourceCulture);
            }
        }
        
        internal static string BindingUnsupportedType {
            get {
                return ResourceManager.GetString("BindingUnsupportedType", resourceCulture);
            }
        }
        
        internal static string ConstructorsNotFound {
            get {
                return ResourceManager.GetString("ConstructorsNotFound", resourceCulture);
            }
        }
        
        internal static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        internal static string DataTypeStringLiteral {
            get {
                return ResourceManager.GetString("DataTypeStringLiteral", resourceCulture);
            }
        }
        
        internal static string Definition {
            get {
                return ResourceManager.GetString("Definition", resourceCulture);
            }
        }
        
        internal static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string ExtensionFailed {
            get {
                return ResourceManager.GetString("ExtensionFailed", resourceCulture);
            }
        }
        
        internal static string ExtensionNotClosed {
            get {
                return ResourceManager.GetString("ExtensionNotClosed", resourceCulture);
            }
        }
        
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        internal static string MethodNotFound {
            get {
                return ResourceManager.GetString("MethodNotFound", resourceCulture);
            }
        }
        
        internal static string MissingConstructor {
            get {
                return ResourceManager.GetString("MissingConstructor", resourceCulture);
            }
        }
        
        internal static string MultiEnumToSbyte {
            get {
                return ResourceManager.GetString("MultiEnumToSbyte", resourceCulture);
            }
        }
        
        internal static string MultipleChild {
            get {
                return ResourceManager.GetString("MultipleChild", resourceCulture);
            }
        }
        
        internal static string NonNullValue {
            get {
                return ResourceManager.GetString("NonNullValue", resourceCulture);
            }
        }
        
        internal static string NoResourceFoundFor {
            get {
                return ResourceManager.GetString("NoResourceFoundFor", resourceCulture);
            }
        }
        
        internal static string ObjectNotFound {
            get {
                return ResourceManager.GetString("ObjectNotFound", resourceCulture);
            }
        }
        
        internal static string Obsolete {
            get {
                return ResourceManager.GetString("Obsolete", resourceCulture);
            }
        }
        
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        internal static string PropertyNotSet {
            get {
                return ResourceManager.GetString("PropertyNotSet", resourceCulture);
            }
        }
        
        internal static string PublicStaticProperty {
            get {
                return ResourceManager.GetString("PublicStaticProperty", resourceCulture);
            }
        }
        
        internal static string RelativeUriOnly {
            get {
                return ResourceManager.GetString("RelativeUriOnly", resourceCulture);
            }
        }
        
        internal static string Requires {
            get {
                return ResourceManager.GetString("Requires", resourceCulture);
            }
        }
        
        internal static string ResolveName {
            get {
                return ResourceManager.GetString("ResolveName", resourceCulture);
            }
        }
        
        internal static string ResolveProperty {
            get {
                return ResourceManager.GetString("ResolveProperty", resourceCulture);
            }
        }
        
        internal static string ResolveType {
            get {
                return ResourceManager.GetString("ResolveType", resourceCulture);
            }
        }
        
        internal static string ResourceAlreadyPresent {
            get {
                return ResourceManager.GetString("ResourceAlreadyPresent", resourceCulture);
            }
        }
        
        internal static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
        
        internal static string ResourceRequireKey {
            get {
                return ResourceManager.GetString("ResourceRequireKey", resourceCulture);
            }
        }
        
        internal static string SetContent {
            get {
                return ResourceManager.GetString("SetContent", resourceCulture);
            }
        }
        
        internal static string SomethingNotFound {
            get {
                return ResourceManager.GetString("SomethingNotFound", resourceCulture);
            }
        }
        
        internal static string StyleOrContent {
            get {
                return ResourceManager.GetString("StyleOrContent", resourceCulture);
            }
        }
        
        internal static string StyleSheet {
            get {
                return ResourceManager.GetString("StyleSheet", resourceCulture);
            }
        }
        
        internal static string Syntax {
            get {
                return ResourceManager.GetString("Syntax", resourceCulture);
            }
        }
        
        internal static string TypeAlreadyContains {
            get {
                return ResourceManager.GetString("TypeAlreadyContains", resourceCulture);
            }
        }
        
        internal static string TypeMismatch {
            get {
                return ResourceManager.GetString("TypeMismatch", resourceCulture);
            }
        }
        
        internal static string TypeName {
            get {
                return ResourceManager.GetString("TypeName", resourceCulture);
            }
        }
        
        internal static string TypeNotFound {
            get {
                return ResourceManager.GetString("TypeNotFound", resourceCulture);
            }
        }
        
        internal static string UndeclaredPrefix {
            get {
                return ResourceManager.GetString("UndeclaredPrefix", resourceCulture);
            }
        }
        
        internal static string UndefinedException {
            get {
                return ResourceManager.GetString("UndefinedException", resourceCulture);
            }
        }
        
        internal static string Unexpected {
            get {
                return ResourceManager.GetString("Unexpected", resourceCulture);
            }
        }
        
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        internal static string Xstatic {
            get {
                return ResourceManager.GetString("Xstatic", resourceCulture);
            }
        }
    }
}
