trigger:
  - none

pr:
  - none

variables:
  - template: /eng/pipelines/common/variables.yml
  - name: provisionator.xcode
    value: '$(System.DefaultWorkingDirectory)/eng/provisioning/xcode.csx'
  - name: provisionator.path
    value: '$(System.DefaultWorkingDirectory)/eng/provisioning/provisioning.csx'
  - name: provisionator.extraArguments
    value: '--v'

resources:
  repositories:
    - repository: xamarin-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
      ref: refs/heads/main # still defaults to master even though main is the main branch
  pipelines:
    - pipeline: handlersci
      source: xamarin-handlers-ci
      trigger:
        branches:
          - main
          - main-handler

stages:

  - stage: android_essentials
    displayName: Essentials (Android)
    dependsOn: []
    jobs:
      - job: device_tests
        workspace:
          clean: all
        displayName: Device Tests
        pool:
          name:  $(macOSXVmPool)
          vmImage: $(macOSXVmImage)
        variables:
          devicetests.project: '$(System.DefaultWorkingDirectory)/src/Essentials/test/DeviceTests.Android/Essentials.DeviceTests.Android.csproj'
        strategy:
          matrix:
            api_30:
              ANDROID_EMULATORS: "system-images;android-30;google_apis;x86"
              devicetests.device: android-emulator-32_30
            api_29:
              ANDROID_EMULATORS: "system-images;android-29;google_apis;x86"
              devicetests.device: android-emulator-32_29
            api_21:
              ANDROID_EMULATORS: "system-images;android-21;google_apis;x86"
              devicetests.device: android-emulator-32_21
        steps:
          - template: common/device-tests.yml
            parameters:
              platform: android

  - stage: android_handlers
    displayName: Handlers (Android)
    dependsOn: []
    jobs:
      - job: device_tests
        workspace:
          clean: all
        displayName: Device Tests
        pool:
          name:  $(macOSXVmPool)
          vmImage: $(macOSXVmImage)
        variables:
          devicetests.project: '$(System.DefaultWorkingDirectory)/src/Core/tests/DeviceTests.Android/Core.DeviceTests.Android.csproj'
        strategy:
          matrix:
            api_30:
              ANDROID_EMULATORS: "system-images;android-30;google_apis;x86"
              devicetests.device: android-emulator-32_30
            api_29:
              ANDROID_EMULATORS: "system-images;android-29;google_apis;x86"
              devicetests.device: android-emulator-32_29
            api_21:
              ANDROID_EMULATORS: "system-images;android-21;google_apis;x86"
              devicetests.device: android-emulator-32_21
        steps:
          - template: common/device-tests.yml
            parameters:
              platform: android

  - stage: ios_essentials
    displayName: Essentials (iOS)
    dependsOn: []
    jobs:
      - job: device_tests
        workspace:
          clean: all
        displayName: Device Tests
        pool:
          name:  $(macOSXVmPool)
          vmImage: $(macOSXVmImage)
        variables:
          devicetests.project: '$(System.DefaultWorkingDirectory)/src/Essentials/test/DeviceTests.iOS/Essentials.DeviceTests.iOS.csproj'
        strategy:
          matrix:
            v14_3:
              devicetests.device: ios-simulator-64_14.3
            # v10_3_1:
            #   devicetests.device: ios-simulator-64_10.3.1
        steps:
          - template: common/device-tests.yml
            parameters:
              platform: ios

  - stage: ios_handlers
    displayName: Handlers (iOS)
    dependsOn: []
    jobs:
      - job: device_tests
        workspace:
          clean: all
        displayName: Device Tests
        pool:
          name:  $(macOSXVmPool)
          vmImage: $(macOSXVmImage)
        variables:
          devicetests.project: '$(System.DefaultWorkingDirectory)/src/Core/tests/DeviceTests.iOS/Core.DeviceTests.iOS.csproj'
        strategy:
          matrix:
            v14_3:
              devicetests.device: ios-simulator-64_14.3
            # v10_3_1:
            #   devicetests.device: ios-simulator-64_10.3.1
        steps:
          - template: common/device-tests.yml
            parameters:
              platform: ios
